### ISSUE TITLE
Unavailable languages reporting being available 

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#1] opened 2022-10-26 01:25 UTC
Some languages like Greek (classical) are reported in the /languages/ endpoint but don't have a table in the directory and returns that error message if used.

**Comment by scossu** [comment] 2023-05-12 13:08
This is caused by misalignment between the index file and the language tables. For example, if a Greek table indeed does not exist, https://github.com/lcnetdev/scriptshifter/blob/main/scriptshifter/tables/data/index.yml#L33-L34 should be removed.

However, in the [test document](https://docs.google.com/spreadsheets/d/1DdBdOUC5AEWvhM3JLVz2r9MA4flrF37j1apD8Grn8IM/edit#gid=0) I see that Greek is active, but the comment indicates major issues. Maybe the table was pulled off at some point? I can't see that anywhere in the git history. Or maybe I tested it locally but did not commit it to git given the poor quality.

**Comment by scossu** [comment] 2023-05-26 07:54
Fixed in 75a12e5c3044443e6931e6dc3d16e84cd8b7db2a.

**Closed by scossu** 2023-05-26 07:54 UTC
