### ISSUE TITLE
Mongolian (Mongol bichig) produces error

### ISSUE THREAD

**Issue by tventimi** [lcnetdev/scriptshifter#128] opened 2024-09-11 19:46 UTC
On both the dev and prod versions, I experience an error when attempting to convert using the "Mongolian (Mongol bichig)" language.  A simple example is converting the text "Mongol" using roman-to-script.  On dev, the error message is "WARNING: An internal error occurred. If the error persists, contact the technical support team."  On prod, it is "Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data".  I do not experience these errors when the same conversion is run with the language set to "Mongolian (Cyrillic)".

**Comment by scossu** [comment] 2024-09-11 21:09
This is caused by a malformed YAML file. I have it fixed in 44fa98a but that's part of a much larger set of changes in test. I can short-cut that fix into main if you need it soon.

**Comment by scossu** [comment] 2024-09-11 23:31
Fixed in #130.

**Closed** 2024-09-11 23:31 UTC
Labels: bug, script
